=== AndreyVSytoss/ProjectElevenTestSample/user-schema.json
{
"$schema": "http://json-schema.org/draft-04/schema#",
"id": "http://example.com/root.json",
"properties": {
"avatar_url": {
"default": "https://avatars1.githubusercontent.com/u/13361572?v=3",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/avatar_url",
"title": "The Avatar_url schema.",
"type": "string"
},
"bio": {
"default": null,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/bio",
"title": "The Bio schema.",
"type": "null"
},
"blog": {
"default": null,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/blog",
"title": "The Blog schema.",
"type": "null"
},
"company": {
"default": null,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/company",
"title": "The Company schema.",
"type": "null"
},
"created_at": {
"default": "2015-07-16T07:08:51Z",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/created_at",
"title": "The Created_at schema.",
"type": "string"
},
"email": {
"default": null,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/email",
"title": "The Email schema.",
"type": "null"
},
"events_url": {
"default": "https://api.github.com/users/AndreyVSytoss/events{/privacy}",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/events_url",
"title": "The Events_url schema.",
"type": "string"
},
"followers": {
"default": 1,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/followers",
"title": "The Followers schema.",
"type": "integer"
},
"followers_url": {
"default": "https://api.github.com/users/AndreyVSytoss/followers",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/followers_url",
"title": "The Followers_url schema.",
"type": "string"
},
"following": {
"default": 0,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/following",
"title": "The Following schema.",
"type": "integer"
},
"following_url": {
"default": "https://api.github.com/users/AndreyVSytoss/following{/other_user}",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/following_url",
"title": "The Following_url schema.",
"type": "string"
},
"gists_url": {
"default": "https://api.github.com/users/AndreyVSytoss/gists{/gist_id}",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/gists_url",
"title": "The Gists_url schema.",
"type": "string"
},
"gravatar_id": {
"default": "",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/gravatar_id",
"title": "The Gravatar_id schema.",
"type": "string"
},
"hireable": {
"default": null,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/hireable",
"title": "The Hireable schema.",
"type": "null"
},
"html_url": {
"default": "https://github.com/AndreyVSytoss",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/html_url",
"title": "The Html_url schema.",
"type": "string"
},
"id": {
"default": 13361572,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/id",
"title": "The Id schema.",
"type": "integer"
},
"location": {
"default": null,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/location",
"title": "The Location schema.",
"type": "null"
},
"login": {
"default": "AndreyVSytoss",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/login",
"title": "The Login schema.",
"type": "string"
},
"name": {
"default": null,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/name",
"title": "The Name schema.",
"type": "null"
},
"organizations_url": {
"default": "https://api.github.com/users/AndreyVSytoss/orgs",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/organizations_url",
"title": "The Organizations_url schema.",
"type": "string"
},
"public_gists": {
"default": 0,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/public_gists",
"title": "The Public_gists schema.",
"type": "integer"
},
"public_repos": {
"default": 7,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/public_repos",
"title": "The Public_repos schema.",
"type": "integer"
},
"received_events_url": {
"default": "https://api.github.com/users/AndreyVSytoss/received_events",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/received_events_url",
"title": "The Received_events_url schema.",
"type": "string"
},
"repos_url": {
"default": "https://api.github.com/users/AndreyVSytoss/repos",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/repos_url",
"title": "The Repos_url schema.",
"type": "string"
},
"site_admin": {
"default": false,
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/site_admin",
"title": "The Site_admin schema.",
"type": "boolean"
},
"starred_url": {
"default": "https://api.github.com/users/AndreyVSytoss/starred{/owner}{/repo}",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/starred_url",
"title": "The Starred_url schema.",
"type": "string"
},
"subscriptions_url": {
"default": "https://api.github.com/users/AndreyVSytoss/subscriptions",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/subscriptions_url",
"title": "The Subscriptions_url schema.",
"type": "string"
},
"type": {
"default": "User",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/type",
"title": "The Type schema.",
"type": "string"
},
"updated_at": {
"default": "2017-03-22T13:29:39Z",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/updated_at",
"title": "The Updated_at schema.",
"type": "string"
},
"url": {
"default": "https://api.github.com/users/AndreyVSytoss",
"description": "An explanation about the purpose of this instance.",
"id": "http://example.com/root.json/url",
"title": "The Url schema.",
"type": "string"
}
},
"type": "object"
}

=== AndreyVSytoss/ProjectElevenTestSample/user.json
{
  "login": "AndreyVSytoss",
  "id": 13361572,
  "avatar_url": "https://avatars1.githubusercontent.com/u/13361572?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/AndreyVSytoss",
  "html_url": "https://github.com/AndreyVSytoss",
  "followers_url": "https://api.github.com/users/AndreyVSytoss/followers",
  "following_url": "https://api.github.com/users/AndreyVSytoss/following{/other_user}",
  "gists_url": "https://api.github.com/users/AndreyVSytoss/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/AndreyVSytoss/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/AndreyVSytoss/subscriptions",
  "organizations_url": "https://api.github.com/users/AndreyVSytoss/orgs",
  "repos_url": "https://api.github.com/users/AndreyVSytoss/repos",
  "events_url": "https://api.github.com/users/AndreyVSytoss/events{/privacy}",
  "received_events_url": "https://api.github.com/users/AndreyVSytoss/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": null,
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 7,
  "public_gists": 0,
  "followers": 1,
  "following": 0,
  "created_at": "2015-07-16T07:08:51Z",
  "updated_at": "2017-03-22T13:29:39Z"
}
